################################################
#                STOCK TERM [v0.1]             #
#                  WILLIAM NOBLE               #
################################################

# Setup Watchlist

watchlist:
  - AAPL
  - MSFT
  - GOOG
  - F
  - KO
  - TSLA

# Setup positions
positions:
  AAPL:
  - 24/02/2020 68.34 23
  - 02/03/2020 72.26 45
  - 03/04/2020 67 07
  MSFT:
  - 01/02/2020 183.89 03
  - 03/07/2020 213.67 74
  - 06/09/2020 223.72 17



